# Generated by Django 4.0 on 2023-09-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=100)),
                ('bike_version', models.CharField(max_length=3)),
                ('bike_model', models.CharField(max_length=30)),
            ],
        ),
    ]
